.headers on
.mode csv
.output compound_new.csv

SELECT DISTINCT FILLIPO.smiles, COMPOUNDS.smiles
FROM COMPOUNDS
LEFT JOIN FILLIPO
USING(smiles)
UNION ALL
SELECT DISTINCT FILLIPO.smiles, COMPOUNDS.smiles
FROM FILLIPO
LEFT JOIN COMPOUNDS
USING(smiles)
WHERE COMPOUNDS.smiles IS NULL
AND FILLIPO.smiles IS NOT NULL
;