name: ci

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env create --file environment.yml
        source activate cytoxnet
        conda list
    - name: Install testing dependencies
      run: |
        pip install flake8 pytest coverage
        pip install flake8-docstrings coveralls
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 cytoxnet --docstring-convention numpy --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 cytoxnet --docstring-convention numpy --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics
    - name: Test coverage with pytest
      run: |
        coverage run --omit="cytoxnet/tests/*" --source="cytoxnet" -m pytest
    - name: Generate coverage report
      run: |
        coverage report
    - name: Coveralls
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true

